version: '3'
services:
  robotk:
    build: .
    env_file: .env
    environment:
      - REDIS_URL=redis://redis:6379
    ports:
      - "8080:8080"
    restart: unless-stopped
  redis:
    image: redis
    ports:
      - "6379:6379"
    restart: unless-stopped
